### ISSUE TITLE
Spread contribution guide to all repositories

### ISSUE THREAD

**Issue by innerjoin** [jazz-community/welcome#1]
We have an awesome contribution guide written by @SBI-. Add a `CONTRIBUTING.md` file to each repository and point to the [Contributing.md](https://github.com/jazz-community/welcome/blob/master/CONTRIBUTING.md) file in this repository. If there are any additional rules to follow, enhance the `CONTRIBUTING.md` file of a specific repository to hold that information

**Comment by innerjoin** [comment]
Place a `CONTRIBUTING.md` in each project that contains source code.
My suggestion would be the following content:

**Required section**
<hr>

# Contributing to <repo name>
Please read our [general contribution guide](). It's content applies to all repositories of the _jazz-community_ organization. 

<hr>

**Optional Section**
<hr>

<place any additional guidance, like quality requirements (test coverage, ...) that are specific to the repository here>

<hr>

**Comment by innerjoin** [comment]
@SBI- Seems to be done for all repos, do you agree?

**Comment by SBI-** [comment]
Git connector is still missing one. I will add one with the next release.

**Comment by innerjoin** [comment]
You are right....
