### ISSUE TITLE
How to get in touch and discuss general topics

### ISSUE THREAD

**Issue by innerjoin** [jazz-community/welcome#2]
As of now, the only way to get in touch with _project members_ and _organization admins_ is only possible through submitting an issue. This is not always a good option, especially if someone has general questions and issues that are not necessarly project issues. Also, if one wants to talk about strategic changes in a repository or about best practices, an issue might also be the wrong place to do so.

For general questions and discussions, I would prefer to switch to another platform. Possible candidates are:
- Gitter
- Slack
- Jazz.net Forum
- **_What else?_**

**Comment by innerjoin** [comment]
**Gitter**
Pros:
- Create public and private chat rooms
- Very easy to use
- Limit access to GitHub users
- A chat badge can be added to any repo, like this:
[![Gitter](https://img.shields.io/badge/chat-on%20gitter-blue.svg)](https://gitter.im/jazz-community/general)

Cons:
- Design is extravagant

**Comment by innerjoin** [comment]
**Slack**
Pros:
- Many 3rd party integrations
- Good app
- feature rich

Cons:
- No _public_ chats meaning that one needs to be invited

**Comment by innerjoin** [comment]
**Jazz.net Forum**
Pros:
- Already known to users
- No additional user account needed
- Possibility to find out users email (e.g. for direct contact)

Cons:
- Terrible text formatting
- Might be not accepted by Jazz.net moderators as it is _out of scope_

**Comment by innerjoin** [comment]
@jazz-community/org-admin What is your opinion on this?

**Comment by SBI-** [comment]
**Forum**: I think github issues already have a lot of the possibilities that the jazz forum offers, and I don't think we'd do ourselves a favor to fragment more-or-less formal discussions and questions between here and jazz.net. I'm in favour of keeping that kind of discussion right with the projects. Also, it might be confusing to have discussions about core IBM features available to everybody mixed in with our custom extensions.

**Informal**: Gitter and Slack (and other irc-like chat services) are better for more informal style conversations. Seeing as how gitter uses github accounts, and everybody who's interested in contributing here will need one, I think we should prefer gitter to slack. It keeps the burden of joining the chat lower, keeping in mind that we can add the link to our repos.

**Comment by MartinBenninger** [comment]
If we are interested in using Slack we should take a look at  [smallchat](https://small.chat/). It provides a simple way to get the conversation started without having to create an account or login anywhere. We could add it to the jazz-community website.

Any messages sent using smallchat are added by a bot to a channel and a new thread is opened for each user. The chat also asks the user for their email so we could invite them to the slack workspace if they are interested in an extended discussion.

Anyway, it's just an idea that we could evaluate if others are also interested.

**Comment by innerjoin** [comment]
As long as the amount of issues and questions is so small, I think we should stick with Github issues and label questions with the `question` label...
