### ISSUE TITLE
New project - CLM Chef cookbook

### ISSUE THREAD

**Issue by lmilbaum** [jazz-community/welcome#9]
I am maintaining a CLM Chef cookbook for deployment automation. 

Here is a link to the repo:
https://github.com/depy-io/clm-chef-cookbook

**Comment by innerjoin** [comment]
Hi Liora,
Thank you for your open source contribution. I'm not really experienced with Chef, but your repostiory looks really promising. I've proposed Pull Request #10 to add your repository to the list of useful repositories, if that is ok for you. 

If a [move of the project into the community organization](https://github.com/jazz-community/welcome/blob/master/CONTRIBUTING.md#move-a-repository-to-jazz-community) is an option for you, I'd suggest to disucss the details in a 1:1 conversation on Linkedin.

**Comment by lmilbaum** [comment]
I am fine with adding the repo to the list of useful repositories. Will get back to you with moving the project into the community organisation. Need to verify with IBM that it works out for them.
